### ISSUE TITLE
Mac上显示效果

### ISSUE THREAD

**Issue by zsqx** [sheencity/shake#1]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/30484671/74118851-1a186380-4bf8-11ea-95f6-5b0fbf0bf927.png">

**Comment by wangzishi** [comment]
Sorry for this poor experience. we did not handle the resize event properly. This will be fixed in future.

At the moment，you can try maximum the windows first before execute the shake program to avoid this issue.

**Comment by zsqx** [comment]
ok  
but it's cool
